# Generated by Django 4.2 on 2023-12-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_created_at_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
    ]
